/**
 * PM2 process manager configuration.
 *
 * Runs ONLY the two server apps of the monorepo:
 *   - api  (NestJS, port 3000, WebSocket/realtime)
 *   - web  (Next.js, port 3001, SSR)
 *
 * The mobile app (apps-mobile/) is intentionally NOT here — it ships to the
 * Play Store, not to the server.
 *
 * Usage (from the repo root on the server):
 *   pnpm install --frozen-lockfile
 *   pnpm build                       # turbo builds api (dist/) and web (.next/)
 *   pnpm --filter api exec prisma migrate deploy
 *   pm2 start deploy/ecosystem.config.js
 *   pm2 save
 */
module.exports = {
  apps: [
    {
      name: "lumac-api",
      cwd: "./apps/api",
      script: "dist/src/main.js",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "400M",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
    },
    {
      name: "lumac-web",
      cwd: "./apps/web",
      // Run the minimal standalone server generated by `next build`.
      script: ".next/standalone/apps/web/server.js",
      interpreter: "node",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "500M",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        HOSTNAME: "127.0.0.1",
        API_ORIGIN: "http://127.0.0.1:3000",
      },
    },
  ],
};
